profiles:
  default:
    duration: 2w
    pass_threshold: 55
    periodic_status_check: "4 days"
    allowed_voters:
      teams:
        - tac
      exclude_team_maintainers: true
    close_on_passing: false
    announcements:
      discussions:
        category: announcements
