profiles:
  default:
    duration: 6w
    pass_threshold: 70
    periodic_status_check: "1 week"
    allowed_voters:
      teams:
        - tac
      exclude_team_maintainers: true
    close_on_passing: true
    announcements:
      discussions:
        category: announcements
