---
name: TI Funding Request Form
description: TI Funding Request Form OpenSSF
title: "[Technical Initiative Funding Request]: "
labels:
  - administration
  - For Review
  - Funding Request
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this Funding Request.
  - type: markdown
    attributes:
      value: |
        **Process:**
        - Please review the process in the [TAC Process Documents](https://github.com/ossf/tac/blob/main/process/TI%20Funding%20Request%20Process.md)
  - type: markdown
    attributes:
      value: "Qualifying information"
  - type: input
    id: TI
    attributes:
      label: Technical Initiative
      description: Which OpenSSF Technical Initiative is requesting the funds?
      placeholder: an existing OpenSSF working group, special interest group, or project
    validations:
      required: true
  - type: input
    id: lifecycle
    attributes:
      label: Lifecycle Phase
      description: What is the lifecycle phase of the requesting Technical Initiative?
      placeholder: sandbox
    validations:
      required: true
  - type: input
    id: amount
    attributes:
      label: Funding amount
      description: What is the exact amount of funding you're requesting?
      placeholder: $1000
    validations:
      required: true
  - type: markdown
    attributes:
      value: "Problem statement - This section aims to set the stage and boundaries
        for the problem you are trying to solve. This is not a place to propose
        solutions, but to define the problem and its impact."
  - type: input
    id: Problem
    attributes:
      label: Problem Statement
      description: What is the problem?
      placeholder: null
    validations:
      required: true
  - type: input
    id: impact
    attributes:
      label: Who does this affect?
      description: Who does this problem impact, and for whom is this solution?
      placeholder: null
    validations:
      required: true
  - type: input
    id: prior
    attributes:
      label: Have there been previous attempts to resolve the problem?
      description: Why is this approach different, or why didn't the other approaches work?
      placeholder: null
    validations:
      required: true
  - type: input
    id: why
    attributes:
      label: Why should it be tackled now and by this TI?
      description: Is this the right place and time for this funding initiative?
      placeholder: null
    validations:
      required: true
  - type: markdown
    attributes:
      value: Proposed work and other work considered - The goal here is to assess the
        feasibility of the proposed work and to understand the alternatives that
        were considered. Such as can be done now and is in scope with the
        current funds.
  - type: textarea
    id: inputs
    attributes:
      label: Give an idea of what is required to make the funding initiative happen
      placeholder: null
    validations:
      required: true
  - type: textarea
    id: deliver
    attributes:
      label: What is going to be needed to deliver this funding initiative?
      placeholder: null
    validations:
      required: true
  - type: textarea
    id: tools
    attributes:
      label: Are there tools or tech that still need to be produced to facilitate the
        funding initiative?
      placeholder: null
    validations:
      required: false
  - type: textarea
    id: requirements
    attributes:
      label: Give a summary of the requirements that contextualize the costs of the
        funding initiative
    validations:
      required: true
  - type: markdown
    attributes:
      value: Covering the planning phase, this next section should provide 
        a relatively detailed plan of how work will start on the funding initiative. This
        section is important because funding initiatives need to get up and running
        quickly.
  - type: markdown
    attributes:
      value: Funding Initiative Plan - It is important to think about setting up collaboration
        platform for code for contributors, reporting framework, license
        decisions, etc.
  - type: input
    id: responsible
    attributes:
      label: Who is responsible for doing the work of this funding initiative?
      description: This person is the primary contact to oversee the idea.
      placeholder: null
    validations:
      required: true
  - type: input
    id: accountable
    attributes:
      label: Who is accountable for doing the work of this funding initiative?
      placeholder: null
    validations:
      required: true
  - type: input
    id: backup
    attributes:
      label: If the responsible or accountable parties are no longer available, what
        is the backup contact or plan?
      placeholder: null
    validations:
      required: true
  - type: input
    id: license
    attributes:
      label: What license is this funding initiative being used under?
      placeholder: null
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [OpenSSF Code of
        Conduct](https://openssf.org/community/code-of-conduct/) to ensure an inclusive environment for participants.
      options:
        - label: I agree to follow the OpenSSF's Code of Conduct
          required: true
  - type: markdown
    attributes:
      value: The final section is to list the Milestones and Approximate costs
        associated with the funding initiative. If you prefer, you can submit a
        Google Sheet or Google Doc in the entry below.
  - type: textarea
    id: Milestones
    attributes:
      label: List the major milestones by date and identify the overall timeline within which the technical initiative plans to accomplish their goals. Any payments for services, sponsorships, etc., will require LF Legal and Financial review.
      placeholder: By the end of quarter 2 of 2025, the GA release will have 500 users
        surveyed for performance assessment completing Milestone 1 for a 5k in funding.
    validations:
      required: true
  - type: textarea
    id: Sow
    attributes:
      label: If this is a request for funding to issue a contract, then OpenSSF will issue that contract. Please provide a Statement of Work (SOW) that we may review. Any contracting action will take 4-6 weeks to issue.
    validations:
      required: false
  - type: markdown
    attributes:
      value: Thanks for completing this form! If you have any problems, questions or
        concerns, please email us at operations@openssf.org
