name: Project Contribution
description: Contribution a Project to the OpenSSF
title: "[Bug]: "
labels: ["administration","For Review"]
projects: ["tac"]
assignees:
  - hythloda
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this Project Contribution!
  - type: input
    id: Maintainers-1
    attributes:
      label: Maintainers-1
      description: Projects must have a minimum of two maintainers with different organization affiliations.
      placeholder: ex. Name GitHub-Id Company
    validations:
      required: true
  - type: input
    id: Maintainers-2
    attributes:
      label: Maintainers-2
      description: Second maintainer
      placeholder: ex. Name GitHub-Id Company
    validations:
      required: true
  - type: textarea
    id: Maintainers-other
    attributes:
      label: Maintainers-other
      description: Other maintainers
      placeholder: ex. Name GitHub-Id Company
    validations:
      required: false
  - type: textarea
    id: mission
    attributes:
      label: Mission
      description: Projects must be aligned with the OpenSSF mission and either be a novel approach for existing areas or address an unfulfilled need. It is expected that the initial code or specification developed by an OpenSSF WG be kept within their repository and will not function as a Project in its own right. Should the initial WG code or specification grow and mature that it warrants its own Project status, then it is subject to Sandbox entry requirements. It is preferred that extensions of an existing OpenSSF project collaborate with the existing project rather than seek a new project.
      placeholder: Project Mission
      value: "The mission of the Project is to "
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: PR-project-lifecycle
    attributes:
      label: Have you made a PR for a new file(s) in the project-lifecycle-documents directory containing all information requested for a project creation? This file must be based on the template for the respective lifecycle stage in the templates directory. The PROJECT_NAME_ prefix of the template must be replaced by the project(s) name.
      multiple: true
      options:
        - Yes
        - No
  - type: dropdown
    id: PR-table-addition
    attributes:
      label: In the above PR have you made a modification of the table listing all projects in the README of this repository by adding the project(s) to the table.
      multiple: true
      options:
        - Yes
        - No
  - type: dropdown
    id: IP-Review
    attributes:
      label: Contributing an existing project to the OpenSSF requires a one-time IP policy and license review with The Linux Foundation. Do you need such a review?
      multiple: true
      options:
        - Yes
        - No
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://openssf.org/community/code-of-conduct/)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true